### ISSUE TITLE
Verificação de variáveis.

### ISSUE THREAD

**Issue by amskywalker** [RaylanderCRibeiro/Sistema-de-ecommerce-php#2]
Na página index.php é interessante que você verifique se as váriaveis tem algum conteúdo

**Comment by RaylanderCRibeiro** [comment]
Muito obg pelo feedback,  vou fazer a verificação sim🙏🙏

Em qua, 30 de set de 2020 22:03, Adailton Moura <notifications@github.com>
escreveu:
