### ISSUE TITLE
README.md sem detalhes

### ISSUE THREAD

**Issue by amskywalker** [RaylanderCRibeiro/Sistema-de-ecommerce-php#3]
Na documentação acrescente alguns detalhes do projeto e também a estrutura de banco de dados.

Estou a disposição para ajudar.

**Comment by RaylanderCRibeiro** [comment]
Poderia me encaminhar um exemplo?

Em qua, 30 de set de 2020 22:04, Adailton Moura <notifications@github.com>
escreveu:

**Comment by amskywalker** [comment]
Minha dica é responda essas três perguntas:

- [ ] O que é o meu projeto?
- [ ] O que outra pessoa precisa para acessá-lo?
- [ ]  Existe alguma observação que essa pessoa deveria saber?

Aqui está alguns repositórios de exemplo.

https://github.com/adailtonmoura/openweathermap
https://github.com/adailtonmoura/QueuesLaravel7

**Comment by RaylanderCRibeiro** [comment]
Muitíssimo obrigado! Me deu um norte total !!!

Em qua, 30 de set de 2020 22:24, Adailton Moura <notifications@github.com>
escreveu:
